### ISSUE TITLE
Latest 3.2.* release break back compatibility

### ISSUE THREAD

**Issue by Troytft** [FriendsOfSymfony/FOSElasticaBundle#1141] opened 2016-09-12 13:35 UTC
You need to include this commit https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/1a1e985d4a17005534141ed7e2d6102c98890f32

**Comment by giovannialbero1992** [comment] 2016-09-12 13:38
Can you give more information about this problem? Thanks

**Comment by alekitto** [comment] 2016-09-12 13:42
Duplicate of #1113

**Comment by Troytft** [comment] 2016-09-12 13:44
if i specify dependency as "friendsofsymfony/elastica-bundle": "^3.1"
And execute "composer update friendsofsymfony/elastica-bundle"
I'll get the update-breaking backward compatibility. 
This contradicts the the rules of the semver.

**Comment by Troytft** [comment] 2016-09-12 13:45
@alekitto bug fixed, but don`t released

**Comment by Troytft** [comment] 2016-09-12 13:54
It is not appropriate to make this kind of changes within a minor release neglecting backwards compatibility

**Comment by XWB** [comment] 2016-09-26 12:08
Did you try the latest 3.2 branch? I cannot release a new version as long as nobody is willing to test it.

**Comment by XWB** [comment] 2016-10-04 12:57
https://github.com/FriendsOfSymfony/FOSElasticaBundle/releases/tag/3.2.1

**Closed by XWB** 2016-10-04 12:57 UTC
