### ISSUE TITLE
Content-Type header missing

### ISSUE THREAD

**Issue by pesseyjulien** [FriendsOfSymfony/FOSElasticaBundle#1267] opened 2017-07-18 13:30 UTC
Hi,

I have a lot of those warnings :

`[WARN ][o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.`

Any idea how to fix this ?

Thanks in advance,
Julien

**Comment by XWB** [comment] 2017-07-26 12:54
I believe this was fixed in Elastica: https://github.com/ruflin/Elastica/commit/d9c59b50bd8ad84689b5e43b4ceef118928c7177

**Comment by kbsali** [comment] 2017-08-04 08:56
@XWB yes but that's Elastica v5.
FOSElasticaBundle v4 depends on Elastica v3.2.3.

Any idea when FOSElasticaBundle v5 might come out? Is it stable enough to go to prod?

**Comment by PapsOu** [comment] 2017-12-15 13:53
The content-type is also mandatory with ES 6.

I've tryed FOSElasticaBundle with https://hub.docker.com/r/sebp/elk/ ELK stack (ES 6), the populate command is failing with the following message : 
```bash
  [Elastica\Exception\ResponseException]                                    
  Content-Type header [application/x-www-form-urlencoded] is not supported
```

More informations about strict content type here https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests

**Comment by Tobion** [comment] 2017-12-16 01:38
FosElasticaBundle 5.0 is going to be released in the next days. Also duplicate of #1317

**Closed by Tobion** 2017-12-16 01:38 UTC
